services:
  catalogo:
    build: .
    environment:

      MONGO_URL: ${MONGO_URL}
      PORT: ${CATALOGO_PORT:-8084}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      SERVE_DOCS: "1"
      
      CATALOGO_BASE_PATH: ${CATALOGO_BASE_PATH:-/catalogo}
      
    ports:
      - "${CATALOGO_PORT:-8084}:${CATALOGO_PORT:-8084}"
      
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${CATALOGO_PORT:-8084}${CATALOGO_BASE_PATH:-/catalogo}/healthz"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
      
    restart: unless-stopped