openapi: 3.0.3
info: { title: API Analítica (Athena), version: "1.0.0" }
servers: [ { url: http://localhost:8086 } ]
paths:
  /kpi/fill-rate:
    get:
      summary: Fill-rate por día y distrito
      parameters:
        - { in: query, name: desde, schema: { type: string, format: date } }
        - { in: query, name: hasta, schema: { type: string, format: date } }
        - { in: query, name: distrito, schema: { type: string } }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    dia: { type: string, format: date }
                    distrito: { type: string }
                    recetado: { type: integer }
                    dispensado: { type: integer }
                    fill_rate: { type: number, format: float }
  /kpi/stockout:
    get:
      summary: Alertas de desabastecimiento (stock_actual <= umbral_reposicion)
      parameters:
        - { in: query, name: desde, schema: { type: string, format: date } }
        - { in: query, name: hasta, schema: { type: string, format: date } }
        - { in: query, name: distrito, schema: { type: string } }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    distrito: { type: string }
                    id_producto: { type: string }
                    stock_actual: { type: integer }
                    umbral_reposicion: { type: integer }
                    alerta: { type: integer }
  /top/quiebres:
    get:
      summary: Top productos en quiebre (rango)
      parameters:
        - { in: query, name: limite, schema: { type: integer, default: 20 } }
        - { in: query, name: desde, schema: { type: string, format: date } }
        - { in: query, name: hasta, schema: { type: string, format: date } }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    codigo_atc: { type: string }
                    nombre: { type: string }
                    dias_en_alerta: { type: integer }
  /kpi/cobertura:
    get:
      summary: Días de cobertura por sucursal/producto
      parameters:
        - { in: query, name: desde, schema: { type: string, format: date } }
        - { in: query, name: hasta, schema: { type: string, format: date } }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_sucursal: { type: integer }
                    id_producto: { type: string }
                    stock_actual: { type: integer }
                    demanda_diaria: { type: number, format: float }
                    dias_cobertura: { type: number, format: float }
