openapi: 3.0.3
info: { title: Orquestador API, version: "1.3.0" }

servers:
  - url: "{basePath}"
    variables:
      basePath: { default: /orquestador }

tags:
  - name: Health
    description: Verificación de estado de salud del servicio y sus dependencias
  - name: Disponibilidad
    description: Consultas combinadas de productos y stock
  - name: Recetas
    description: Orquestación de validaciones de recetas

paths:
  /healthz:
    get:
      tags: [Health]
      summary: Health check básico (liveness)
      responses: { "200": { description: OK } }

  /disponibilidad:
    get:
      tags: [Disponibilidad]
      summary: Buscar disponibilidad de productos en un distrito
      description: "Combina una búsqueda en Catálogo con una consulta de stock en Inventario."
      parameters:
        - name: producto
          in: query
          required: false
          schema: { type: string }
          description: ID exacto del producto a buscar.
        - name: keyword 
          in: query
          required: false
          schema: { type: string }
          description: Texto libre para buscar en el nombre o keywords del Catálogo.
        - name: distrito
          in: query
          required: true
          schema: { type: string }
          description: Distrito donde buscar el stock.
        - name: stock_minimo
          in: query
          required: false
          schema: { type: integer, default: 1 }
          description: Filtra sucursales con stock mayor o igual a este valor.
      responses:
        "200": { description: OK }
        "400": { description: Faltan parámetros requeridos }
        "502": { description: Error en un servicio externo }

  /ficha-producto/{productoId}:
    get:
      tags: [Disponibilidad]
      summary: Obtener ficha completa de un producto con stock agregado por distrito
      parameters:
        - name: productoId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
        "404": { description: Producto no encontrado }
        "502": { description: Error en un servicio externo }

  /receta/validar:
    post:
      tags: [Recetas]
      summary: Pre-validar el stock en una sucursal para una receta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id_receta]
              properties:
                id_receta: { type: integer }
      responses:
        "200": { description: OK (con estado sugerido) }
        "400": { description: Falta id_receta }
        "404": { description: Receta no encontrada }
        "502": { description: Error en un servicio externo }