services:
  orquestador:
    build: .
    container_name: orquestador-api 
    ports:
      - "${ORQUESTADOR_PORT:-8085}:8085"
    environment:
      ORQUESTADOR_BASE_PATH: ${ORQUESTADOR_BASE_PATH:-/orquestador}
      PORT: ${ORQUESTADOR_PORT:-8085}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      SERVE_DOCS: "1"

      INVENTARIO_URL: ${INVENTARIO_URL}
      RECETAS_URL: ${RECETAS_URL}
      CATALOGO_URL: ${CATALOGO_URL}
      
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8085${ORQUESTADOR_BASE_PATH:-/orquestador}/healthz"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped