version: "3.9"
services:
  orquestador:
    build: .
    environment:
      INVENTARIO_URL: ${INVENTARIO_URL:-http://${ALB_DNS}${INVENTARIO_BASE_PATH}}
      RECETAS_URL:    ${RECETAS_URL:-http://${ALB_DNS}${RECETAS_BASE_PATH}}
      CATALOGO_URL:   ${CATALOGO_URL:-http://${ALB_DNS}${CATALOGO_BASE_PATH}}
      PORT: ${ORQUESTADOR_PORT:-8085}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      SERVE_DOCS: "1"
      BASE_PATH: ${ORQUESTADOR_BASE_PATH:-/orquestador}
    ports: ["8085:8085"]
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:8085${ORQUESTADOR_BASE_PATH}/healthz"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
