services:
  recetas:
    build: .
    container_name: recetas-api
    ports:
      - "${RECETAS_PORT:-8083}:8083"
    environment:

      MYSQL_URL: ${MYSQL_URL}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      RECETAS_BASE_PATH: ${RECETAS_BASE_PATH:-/recetas} 

      CATALOGO_BASE_URL: ${CATALOGO_BASE_URL}
      INVENTARIO_BASE_URL: ${INVENTARIO_BASE_URL}

      VALIDATE_PRODUCTO: "1"
      VALIDATE_SUCURSAL: "1"

    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:8083${RECETAS_BASE_PATH:-/recetas}/healthz"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped