version: "3.9"
services:
  recetas:
    build: .
    environment:
      MYSQL_URL: ${MYSQL_URL}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      SERVE_DOCS: "1"
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:8083/healthz"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
