server:
  port: 8082
  servlet:
    context-path: ${BASE_PATH:/inventario}

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:inventario}
    username: ${PG_USER:inventario}
    password: ${PG_PASSWORD:inventario}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true

cors:
  origins: ${CORS_ORIGINS:*}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    # el UI vive aquí
    path: /docs
    # y carga tu YAML estático por defecto
    url: /openapi/inventario.yaml
    # deja el buscador con la URL por defecto (opcional)
    disable-swagger-default-url: false

# donde montas el YAML dentro del contenedor
docs:
  dir: ${DOCS_DIR:/app/docs}

# (sigue igual) integración con Catálogo
catalogo:
  base-url: ${CATALOGO_BASE_URL:http://localhost:8084/catalogo}
  validate-product: ${CATALOGO_VALIDATE_PRODUCT:true}
