server:
  port: 8082
  servlet:
    # deja /inventario por defecto; igual puedes override con BASE_PATH
    context-path: ${BASE_PATH:/inventario}

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:inventario}
    username: ${PG_USER:inventario}
    password: ${PG_PASSWORD:inventario}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

  mvc:
    # para que podamos capturar 404 en el handler (NoHandlerFoundException)
    throw-exception-if-no-handler-found: true

cors:
  origins: ${CORS_ORIGINS:*}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    # >>> El UI vivirá en /inventario/docs
    path: /docs
    # >>> El UI cargará este YAML
    url: /openapi/inventario.yaml

# Ruta del directorio donde montas el YAML (docker: /app/docs)
docs:
  dir: ${DOCS_DIR:/app/docs}
