server:
  port: 8082
  servlet:
    context-path: ${BASE_PATH:/inventario}

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:inventario}
    username: ${PG_USER:inventario}
    password: ${PG_PASSWORD:inventario}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

  mvc:
    throw-exception-if-no-handler-found: true

cors:
  origins: ${CORS_ORIGINS:*}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    # 游녢 Deja el buscador vac칤o y NO muestra el link debajo del t칤tulo
    disable-swagger-default-url: true
    # (IMPORTANTE) No pongas "url:" aqu칤. El spec seguir치 disponible en /inventario/openapi/inventario.yaml

# Directorio donde sirves el YAML est치tico
docs:
  dir: ${DOCS_DIR:/app/docs}

# 游댕 Config de integraci칩n con Cat치logo (se lee de variables de entorno)
catalogo:
  base-url: ${CATALOGO_BASE_URL:http://localhost:8084/catalogo}
  validate-product: ${CATALOGO_VALIDATE_PRODUCT:true}
