server:
  port: 8082
  servlet:
    context-path: ${BASE_PATH:}   # <- soporta /inventario

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:inventario}
    username: ${PG_USER:inventario}
    password: ${PG_PASSWORD:inventario}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

cors:
  origins: ${CORS_ORIGINS:*}

springdoc:
  api-docs:
    enabled: true
  # Este path es relativo al context-path; no hace falta repetir BASE_PATH.
  swagger-ui:
    url: /docs/inventario.yaml

docs:
  dir: ${DOCS_DIR:/app/docs}
