openapi: 3.0.3
info:
  title: Inventario y Sucursales API
  version: "1.2.0"

servers:
  - url: http://{host}:{port}{basePath}
    variables:
      host:
        default: localhost
      port:
        default: "8082"
      basePath:
        default: /inventario

tags:
  - name: Health
  - name: Sucursales
  - name: Stocks
  - name: Movimientos

paths:
  /healthz:
    get:
      tags:
        - Health
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

  /sucursales:
    get:
      tags:
        - Sucursales
      summary: Listar sucursales (filtrable por distrito)
      parameters:
        - in: query
          name: distrito
          schema:
            type: string
          description: Filtra por distrito (coincidencia exacta, case-insensitive).
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sucursal"

    post:
      tags:
        - Sucursales
      summary: Crear sucursal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SucursalCreate"
      responses:
        "201":
          description: Creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sucursal"
        "400":
          description: Datos inválidos
        "409":
          description: Conflicto (ID existente)

  /sucursales/{id_sucursal}:
    put:
      tags:
        - Sucursales
      summary: Actualizar datos de una sucursal
      parameters:
        - in: path
          name: id_sucursal
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SucursalUpdate"
      responses:
        "200":
          description: Actualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sucursal"
        "400":
          description: Datos inválidos
        "404":
          description: No existe

  /stock:
    get:
      tags:
        - Stocks
      summary: Listar stock (filtrable)
      parameters:
        - in: query
          name: id_producto
          schema:
            type: string
          description: ID canónico del producto (Catálogo).
        - in: query
          name: id_sucursal
          schema:
            type: integer
          description: ID de sucursal.
        - in: query
          name: distrito
          schema:
            type: string
          description: Filtra por distrito (usa sucursales del distrito).
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StockItem"

    patch:
      tags:
        - Stocks
      summary: Ajuste de stock (positivo/negativo) para un producto en una sucursal
      description: |
        Preferido: campo `ajuste` (entero, puede ser negativo).
        Compatibilidad: también se admite `delta` (deprecado).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id_sucursal
                - id_producto
                - ajuste
              properties:
                id_sucursal:
                  type: integer
                id_producto:
                  type: string
                ajuste:
                  type: integer
                  description: Variación de stock. Puede ser negativa.
                delta:
                  type: integer
                  description: Alias legado de 'ajuste'.
                  deprecated: true
                motivo:
                  type: string
                  nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StockItem"
        "400":
          description: Stock insuficiente o datos inválidos
        "404":
          description: No existe stock (o sucursal/producto)

  /movimientos:
    get:
      tags:
        - Movimientos
      summary: Listar movimientos de stock
      parameters:
        - in: query
          name: producto_id
          schema:
            type: string
        - in: query
          name: sucursal_id
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movimiento"

    post:
      tags:
        - Movimientos
      summary: Crear movimiento (ENTRADA/EGRESO) y aplicar al stock
      description: >
        Si (sucursal, producto) no existe y el tipo es ENTRADA, se crea
        automáticamente la fila en `stock` con `umbral_reposicion=0`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MovimientoCreate"
      responses:
        "201":
          description: Creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movimiento"
        "400":
          description: Stock insuficiente / datos inválidos
        "404":
          description: No existe (para EGRESO sin stock base)

components:
  schemas:
    Sucursal:
      type: object
      properties:
        id_sucursal:
          type: integer
        nombre:
          type: string
        distrito:
          type: string
        direccion:
          type: string
          nullable: true

    SucursalCreate:
      type: object
      required:
        - id_sucursal
        - nombre
        - distrito
        - direccion
      properties:
        id_sucursal:
          type: integer
          minimum: 1
        nombre:
          type: string
          minLength: 1
        distrito:
          type: string
          minLength: 1
        direccion:
          type: string
          minLength: 1

    SucursalUpdate:
      type: object
      required:
        - nombre
        - distrito
        - direccion
      properties:
        nombre:
          type: string
          minLength: 1
        distrito:
          type: string
          minLength: 1
        direccion:
          type: string
          minLength: 1

    StockItem:
      type: object
      properties:
        id_sucursal:
          type: integer
        id_producto:
          type: string
        stock_actual:
          type: integer
        umbral_reposicion:
          type: integer
        fecha_actualizacion:
          type: string
          format: date-time

    Movimiento:
      type: object
      properties:
        id:
          type: integer
        id_sucursal:
          type: integer
        id_producto:
          type: string
        tipo_movimiento:
          type: string
          enum:
            - ENTRADA
            - EGRESO
        cantidad:
          type: integer
        fecha_movimiento:
          type: string
          format: date-time
        motivo:
          type: string
          nullable: true

    MovimientoCreate:
      type: object
      required:
        - id_sucursal
        - id_producto
        - tipo_movimiento
        - cantidad
      properties:
        id_sucursal:
          type: integer
        id_producto:
          type: string
        tipo_movimiento:
          type: string
          enum:
            - ENTRADA
            - EGRESO
        cantidad:
          type: integer
          minimum: 1
        motivo:
          type: string
          nullable: true
