services:
  inventario:
    build: .
    container_name: inventario-api
    ports:
      - "8082:8082"
    environment:
      BASE_PATH: ${INVENTARIO_BASE_PATH:-/inventario}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT:-5432}
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      DOCS_DIR: /app/docs

      CATALOGO_BASE_URL: ${CATALOGO_BASE_URL}
      CATALOGO_VALIDATE_PRODUCT:

    volumes:
      - ./docs:/app/docs:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8082$${BASE_PATH:-/inventario}/healthz || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped